enchants:
  - sharpness
  - smite
  - bane_of_arthropods
  - fire_aspect
  - knockback
  - sweeping
  - looting
  - power
  - punch
  - flame
  - infinity
  - impaling
  - riptide
  - loyalty
  - channeling
  - efficiency
  - fortune
  - silk_touch
  - frost_walker
  - depth_strider
  - luck_of_the_sea
  - lure
  - piercing
  - quick_charge
  - multishot
  - protection
  - blast_protection
  - fire_protection
  - projectile_protection
  - feather_falling
  - aqua_affinity
  - respiration
  - soul_speed
  - swift_sneak
  - thorns
  - unbreaking
  - mending
  - vanishing_curse
  - binding_curse